import { Task, Settings, Delegate } from '@/types';

export const mockDelegates: Delegate[] = [
  { name: 'Marketing VA', role: 'Virtual Assistant', capabilities: ['marketing'] },
  { name: 'Sales SDR', role: 'Sales Development', capabilities: ['sales'] },
  { name: 'Ops Manager', role: 'Operations', capabilities: ['operations', 'finance'] },
  { name: 'AI Agent', role: 'Automation', capabilities: ['marketing', 'operations', 'finance'] },
  { name: 'Recruiter', role: 'Talent', capabilities: ['hiring'] },
];

export const mockSettings: Settings = {
  founderName: 'Peter',
  deepWorkHours: 3,
  delegates: mockDelegates,
  companyName: '',
  companyDescription: '',
  companyStage: '',
  currentRevenue: '',
  quarterlyGoals: ['', '', ''],
  biggestBottleneck: '',
  pipelineStatus: '',
  founderSuperpower: '',
  avoidDelegate: '',
  slackChannels: [
    { id: 'C0A9HBGVADP', name: 'straion-marketing' },
    { id: 'G1GAGFVEW', name: 'founders' },
  ],
};

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Close deal with Enterprise prospect (Acme Corp)',
    description: 'Final negotiation call. They want custom pricing. $120k ARR at stake. Only Peter can approve the terms.',
    category: 'sales',
    urgency: 5,
    revenueImpact: 5,
    leverage: 4,
    founderOnly: true,
    estimatedHours: 1,
    deadline: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    status: 'inbox',
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Review and approve product roadmap for Q2',
    description: 'Engineering needs sign-off on Q2 priorities. Blocks 4 engineers for the quarter.',
    category: 'product',
    urgency: 4,
    revenueImpact: 4,
    leverage: 5,
    founderOnly: true,
    estimatedHours: 1.5,
    deadline: new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0],
    status: 'inbox',
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Record founder video for LinkedIn campaign',
    description: 'Short 2-min video explaining the vision. Marketing team will handle editing and distribution.',
    category: 'marketing',
    urgency: 3,
    revenueImpact: 3,
    leverage: 4,
    founderOnly: true,
    estimatedHours: 0.5,
    deadline: new Date(Date.now() + 5 * 86400000).toISOString().split('T')[0],
    status: 'inbox',
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Write blog post about industry trends',
    description: 'SEO content piece about accessibility trends in 2024. Can be drafted by anyone.',
    category: 'marketing',
    urgency: 2,
    revenueImpact: 2,
    leverage: 3,
    founderOnly: false,
    estimatedHours: 2,
    status: 'inbox',
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Update CRM pipeline stages',
    description: 'Sales team requested new pipeline stages. Admin work in HubSpot.',
    category: 'sales',
    urgency: 2,
    revenueImpact: 1,
    leverage: 2,
    founderOnly: false,
    estimatedHours: 1,
    status: 'inbox',
    createdAt: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Prepare investor update email',
    description: 'Monthly investor update with metrics, wins, and asks. Investors expect it by Friday.',
    category: 'finance',
    urgency: 3,
    revenueImpact: 2,
    leverage: 3,
    founderOnly: true,
    estimatedHours: 1,
    deadline: new Date(Date.now() + 4 * 86400000).toISOString().split('T')[0],
    status: 'inbox',
    createdAt: new Date().toISOString(),
  },
  {
    id: '7',
    title: 'Fix broken analytics tracking',
    description: 'Google Analytics events stopped firing after last deploy. Need debugging.',
    category: 'product',
    urgency: 3,
    revenueImpact: 2,
    leverage: 2,
    founderOnly: false,
    estimatedHours: 2,
    status: 'inbox',
    createdAt: new Date().toISOString(),
  },
  {
    id: '8',
    title: 'Schedule team offsite',
    description: 'Book venue, plan agenda for quarterly team offsite next month.',
    category: 'operations',
    urgency: 1,
    revenueImpact: 1,
    leverage: 2,
    founderOnly: false,
    estimatedHours: 3,
    status: 'inbox',
    createdAt: new Date().toISOString(),
  },
  {
    id: '9',
    title: 'Review 3 engineering candidates',
    description: 'Screen resumes and decide who to bring to final round.',
    category: 'hiring',
    urgency: 3,
    revenueImpact: 3,
    leverage: 4,
    founderOnly: true,
    estimatedHours: 1,
    deadline: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
    status: 'inbox',
    createdAt: new Date().toISOString(),
  },
  {
    id: '10',
    title: 'Respond to partnership inquiry from TechCo',
    description: 'Inbound partnership request. Could be strategic but unclear ROI.',
    category: 'sales',
    urgency: 2,
    revenueImpact: 3,
    leverage: 3,
    founderOnly: false,
    estimatedHours: 0.5,
    status: 'inbox',
    createdAt: new Date().toISOString(),
  },
];
